[package]
name = "rrconsumer"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
rabbitmq-stream-client = "*"
bytes = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
serde_amqp = "*"
tracing = "*"
tracing-subscriber = "*"
anyhow = "*"
tokio = { version = "1.47.1", features = ['full'] }
uuid = { version = "1", features = ["serde", "v4"] }
dotenv = "0.15.0"
prost = "*"
tonic-prost = "*"
prost-types = { version = "*" }
tonic = "0.14.2"
tigerbeetle-unofficial = "0.14.17"
chrono = "*"
[build-dependencies]
tonic-prost-build = "*"
tonic-build = "0.14.2"

[[example]]
name = "test_producer"
path = "src/examples/testproducer.rs"
