// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: task.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_UNKNOWN          TaskType = 0
	TaskType_CREATE_ACCOUNT   TaskType = 1
	TaskType_BATCH_ACCOUNTS   TaskType = 2
	TaskType_LOOKUP_ACCOUNTS  TaskType = 3
	TaskType_CREATE_TRANSFER  TaskType = 4
	TaskType_BATCH_TRANSFERS  TaskType = 5
	TaskType_LOOKUP_TRANSFERS TaskType = 6
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATE_ACCOUNT",
		2: "BATCH_ACCOUNTS",
		3: "LOOKUP_ACCOUNTS",
		4: "CREATE_TRANSFER",
		5: "BATCH_TRANSFERS",
		6: "LOOKUP_TRANSFERS",
	}
	TaskType_value = map[string]int32{
		"UNKNOWN":          0,
		"CREATE_ACCOUNT":   1,
		"BATCH_ACCOUNTS":   2,
		"LOOKUP_ACCOUNTS":  3,
		"CREATE_TRANSFER":  4,
		"BATCH_TRANSFERS":  5,
		"LOOKUP_TRANSFERS": 6,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

// Main Task Request - Flattened for 2025 compatibility
type TaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- Metadata ---
	Id         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskType   TaskType `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3,enum=task.TaskType" json:"task_type,omitempty"` // e.g., "create_account", "create_transfer", "batch_accounts"
	CreatedAt  int64    `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Priority   *uint32  `protobuf:"varint,4,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	RetryCount *int32   `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3,oneof" json:"retry_count,omitempty"`
	// --- Common TigerBeetle Fields (Optional) ---
	Ledger *uint32 `protobuf:"varint,10,opt,name=ledger,proto3,oneof" json:"ledger,omitempty"`
	Code   *uint32 `protobuf:"varint,11,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Flags  *uint32 `protobuf:"varint,12,opt,name=flags,proto3,oneof" json:"flags,omitempty"`
	// --- Identifiers (Optional) ---
	AccountId       *UInt128 `protobuf:"bytes,20,opt,name=account_id,json=accountId,proto3,oneof" json:"account_id,omitempty"`
	TransferId      *UInt128 `protobuf:"bytes,21,opt,name=transfer_id,json=transferId,proto3,oneof" json:"transfer_id,omitempty"`
	DebitAccountId  *UInt128 `protobuf:"bytes,22,opt,name=debit_account_id,json=debitAccountId,proto3,oneof" json:"debit_account_id,omitempty"`
	CreditAccountId *UInt128 `protobuf:"bytes,23,opt,name=credit_account_id,json=creditAccountId,proto3,oneof" json:"credit_account_id,omitempty"`
	PendingId       *UInt128 `protobuf:"bytes,24,opt,name=pending_id,json=pendingId,proto3,oneof" json:"pending_id,omitempty"`
	// --- Transactional Data (Optional) ---
	Amount  *UInt128 `protobuf:"bytes,30,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	Timeout *uint64  `protobuf:"varint,31,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	// --- User Data (Optional) ---
	UserData_128 *UInt128 `protobuf:"bytes,40,opt,name=user_data_128,json=userData128,proto3,oneof" json:"user_data_128,omitempty"`
	UserData_64  *uint64  `protobuf:"varint,41,opt,name=user_data_64,json=userData64,proto3,oneof" json:"user_data_64,omitempty"`
	UserData_32  *uint32  `protobuf:"varint,42,opt,name=user_data_32,json=userData32,proto3,oneof" json:"user_data_32,omitempty"`
	// --- Batching & Queries (Optional) ---
	AccountBatch  []*CreateAccountRequest  `protobuf:"bytes,50,rep,name=account_batch,json=accountBatch,proto3" json:"account_batch,omitempty"`
	TransferBatch []*CreateTransferRequest `protobuf:"bytes,51,rep,name=transfer_batch,json=transferBatch,proto3" json:"transfer_batch,omitempty"`
	LookupIds     []*UInt128               `protobuf:"bytes,52,rep,name=lookup_ids,json=lookupIds,proto3" json:"lookup_ids,omitempty"`
	Limit         *uint32                  `protobuf:"varint,53,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskRequest) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_UNKNOWN
}

func (x *TaskRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TaskRequest) GetPriority() uint32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *TaskRequest) GetRetryCount() int32 {
	if x != nil && x.RetryCount != nil {
		return *x.RetryCount
	}
	return 0
}

func (x *TaskRequest) GetLedger() uint32 {
	if x != nil && x.Ledger != nil {
		return *x.Ledger
	}
	return 0
}

func (x *TaskRequest) GetCode() uint32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *TaskRequest) GetFlags() uint32 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

func (x *TaskRequest) GetAccountId() *UInt128 {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *TaskRequest) GetTransferId() *UInt128 {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *TaskRequest) GetDebitAccountId() *UInt128 {
	if x != nil {
		return x.DebitAccountId
	}
	return nil
}

func (x *TaskRequest) GetCreditAccountId() *UInt128 {
	if x != nil {
		return x.CreditAccountId
	}
	return nil
}

func (x *TaskRequest) GetPendingId() *UInt128 {
	if x != nil {
		return x.PendingId
	}
	return nil
}

func (x *TaskRequest) GetAmount() *UInt128 {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *TaskRequest) GetTimeout() uint64 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

func (x *TaskRequest) GetUserData_128() *UInt128 {
	if x != nil {
		return x.UserData_128
	}
	return nil
}

func (x *TaskRequest) GetUserData_64() uint64 {
	if x != nil && x.UserData_64 != nil {
		return *x.UserData_64
	}
	return 0
}

func (x *TaskRequest) GetUserData_32() uint32 {
	if x != nil && x.UserData_32 != nil {
		return *x.UserData_32
	}
	return 0
}

func (x *TaskRequest) GetAccountBatch() []*CreateAccountRequest {
	if x != nil {
		return x.AccountBatch
	}
	return nil
}

func (x *TaskRequest) GetTransferBatch() []*CreateTransferRequest {
	if x != nil {
		return x.TransferBatch
	}
	return nil
}

func (x *TaskRequest) GetLookupIds() []*UInt128 {
	if x != nil {
		return x.LookupIds
	}
	return nil
}

func (x *TaskRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type UInt128 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Low           uint64                 `protobuf:"fixed64,1,opt,name=low,proto3" json:"low,omitempty"`
	High          uint64                 `protobuf:"fixed64,2,opt,name=high,proto3" json:"high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UInt128) Reset() {
	*x = UInt128{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UInt128) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInt128) ProtoMessage() {}

func (x *UInt128) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInt128.ProtoReflect.Descriptor instead.
func (*UInt128) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *UInt128) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *UInt128) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

// Still used within account_batch
type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UInt128               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ledger        uint32                 `protobuf:"varint,2,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Code          uint32                 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	UserData_128  *UInt128               `protobuf:"bytes,4,opt,name=user_data_128,json=userData128,proto3,oneof" json:"user_data_128,omitempty"`
	UserData_64   *uint64                `protobuf:"varint,5,opt,name=user_data_64,json=userData64,proto3,oneof" json:"user_data_64,omitempty"`
	UserData_32   *uint32                `protobuf:"varint,6,opt,name=user_data_32,json=userData32,proto3,oneof" json:"user_data_32,omitempty"`
	Flags         *uint32                `protobuf:"varint,7,opt,name=flags,proto3,oneof" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountRequest) GetId() *UInt128 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateAccountRequest) GetLedger() uint32 {
	if x != nil {
		return x.Ledger
	}
	return 0
}

func (x *CreateAccountRequest) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateAccountRequest) GetUserData_128() *UInt128 {
	if x != nil {
		return x.UserData_128
	}
	return nil
}

func (x *CreateAccountRequest) GetUserData_64() uint64 {
	if x != nil && x.UserData_64 != nil {
		return *x.UserData_64
	}
	return 0
}

func (x *CreateAccountRequest) GetUserData_32() uint32 {
	if x != nil && x.UserData_32 != nil {
		return *x.UserData_32
	}
	return 0
}

func (x *CreateAccountRequest) GetFlags() uint32 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

// Still used within transfer_batch
type CreateTransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              *UInt128               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DebitAccountId  *UInt128               `protobuf:"bytes,2,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId *UInt128               `protobuf:"bytes,3,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          *UInt128               `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PendingId       *UInt128               `protobuf:"bytes,5,opt,name=pending_id,json=pendingId,proto3,oneof" json:"pending_id,omitempty"`
	Ledger          *uint32                `protobuf:"varint,6,opt,name=ledger,proto3,oneof" json:"ledger,omitempty"`
	Code            *uint32                `protobuf:"varint,7,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Flags           *uint32                `protobuf:"varint,8,opt,name=flags,proto3,oneof" json:"flags,omitempty"`
	Timeout         *uint64                `protobuf:"varint,9,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTransferRequest) GetId() *UInt128 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateTransferRequest) GetDebitAccountId() *UInt128 {
	if x != nil {
		return x.DebitAccountId
	}
	return nil
}

func (x *CreateTransferRequest) GetCreditAccountId() *UInt128 {
	if x != nil {
		return x.CreditAccountId
	}
	return nil
}

func (x *CreateTransferRequest) GetAmount() *UInt128 {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateTransferRequest) GetPendingId() *UInt128 {
	if x != nil {
		return x.PendingId
	}
	return nil
}

func (x *CreateTransferRequest) GetLedger() uint32 {
	if x != nil && x.Ledger != nil {
		return *x.Ledger
	}
	return 0
}

func (x *CreateTransferRequest) GetCode() uint32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *CreateTransferRequest) GetFlags() uint32 {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return 0
}

func (x *CreateTransferRequest) GetTimeout() uint64 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

type TaskResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskType       string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	AccountResult  *AccountResult         `protobuf:"bytes,5,opt,name=account_result,json=accountResult,proto3,oneof" json:"account_result,omitempty"`
	TransferResult *TransferResult        `protobuf:"bytes,6,opt,name=transfer_result,json=transferResult,proto3,oneof" json:"transfer_result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskResponse) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskResponse) GetAccountResult() *AccountResult {
	if x != nil {
		return x.AccountResult
	}
	return nil
}

func (x *TaskResponse) GetTransferResult() *TransferResult {
	if x != nil {
		return x.TransferResult
	}
	return nil
}

type Account struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *UInt128               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DebitsPending  *UInt128               `protobuf:"bytes,2,opt,name=debits_pending,json=debitsPending,proto3" json:"debits_pending,omitempty"`
	DebitsPosted   *UInt128               `protobuf:"bytes,3,opt,name=debits_posted,json=debitsPosted,proto3" json:"debits_posted,omitempty"`
	CreditsPending *UInt128               `protobuf:"bytes,4,opt,name=credits_pending,json=creditsPending,proto3" json:"credits_pending,omitempty"`
	CreditsPosted  *UInt128               `protobuf:"bytes,5,opt,name=credits_posted,json=creditsPosted,proto3" json:"credits_posted,omitempty"`
	Ledger         uint32                 `protobuf:"varint,6,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Code           uint32                 `protobuf:"varint,7,opt,name=code,proto3" json:"code,omitempty"`
	Flags          uint32                 `protobuf:"varint,8,opt,name=flags,proto3" json:"flags,omitempty"`
	Timestamp      uint64                 `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

func (x *Account) GetId() *UInt128 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Account) GetDebitsPending() *UInt128 {
	if x != nil {
		return x.DebitsPending
	}
	return nil
}

func (x *Account) GetDebitsPosted() *UInt128 {
	if x != nil {
		return x.DebitsPosted
	}
	return nil
}

func (x *Account) GetCreditsPending() *UInt128 {
	if x != nil {
		return x.CreditsPending
	}
	return nil
}

func (x *Account) GetCreditsPosted() *UInt128 {
	if x != nil {
		return x.CreditsPosted
	}
	return nil
}

func (x *Account) GetLedger() uint32 {
	if x != nil {
		return x.Ledger
	}
	return 0
}

func (x *Account) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Account) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Account) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AccountResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResult) Reset() {
	*x = AccountResult{}
	mi := &file_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResult) ProtoMessage() {}

func (x *AccountResult) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResult.ProtoReflect.Descriptor instead.
func (*AccountResult) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{6}
}

func (x *AccountResult) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *AccountResult) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Transfer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              *UInt128               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DebitAccountId  *UInt128               `protobuf:"bytes,2,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId *UInt128               `protobuf:"bytes,3,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          *UInt128               `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Ledger          uint32                 `protobuf:"varint,5,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Code            uint32                 `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`
	Flags           uint32                 `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`
	Timestamp       uint64                 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{7}
}

func (x *Transfer) GetId() *UInt128 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Transfer) GetDebitAccountId() *UInt128 {
	if x != nil {
		return x.DebitAccountId
	}
	return nil
}

func (x *Transfer) GetCreditAccountId() *UInt128 {
	if x != nil {
		return x.CreditAccountId
	}
	return nil
}

func (x *Transfer) GetAmount() *UInt128 {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Transfer) GetLedger() uint32 {
	if x != nil {
		return x.Ledger
	}
	return 0
}

func (x *Transfer) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Transfer) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Transfer) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TransferResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*Transfer            `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResult) Reset() {
	*x = TransferResult{}
	mi := &file_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResult) ProtoMessage() {}

func (x *TransferResult) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResult.ProtoReflect.Descriptor instead.
func (*TransferResult) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{8}
}

func (x *TransferResult) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

func (x *TransferResult) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\x04task\"\xa2\t\n" +
	"\vTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\ttask_type\x18\x02 \x01(\x0e2\x0e.task.TaskTypeR\btaskType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\bpriority\x18\x04 \x01(\rH\x00R\bpriority\x88\x01\x01\x12$\n" +
	"\vretry_count\x18\x05 \x01(\x05H\x01R\n" +
	"retryCount\x88\x01\x01\x12\x1b\n" +
	"\x06ledger\x18\n" +
	" \x01(\rH\x02R\x06ledger\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\v \x01(\rH\x03R\x04code\x88\x01\x01\x12\x19\n" +
	"\x05flags\x18\f \x01(\rH\x04R\x05flags\x88\x01\x01\x121\n" +
	"\n" +
	"account_id\x18\x14 \x01(\v2\r.task.UInt128H\x05R\taccountId\x88\x01\x01\x123\n" +
	"\vtransfer_id\x18\x15 \x01(\v2\r.task.UInt128H\x06R\n" +
	"transferId\x88\x01\x01\x12<\n" +
	"\x10debit_account_id\x18\x16 \x01(\v2\r.task.UInt128H\aR\x0edebitAccountId\x88\x01\x01\x12>\n" +
	"\x11credit_account_id\x18\x17 \x01(\v2\r.task.UInt128H\bR\x0fcreditAccountId\x88\x01\x01\x121\n" +
	"\n" +
	"pending_id\x18\x18 \x01(\v2\r.task.UInt128H\tR\tpendingId\x88\x01\x01\x12*\n" +
	"\x06amount\x18\x1e \x01(\v2\r.task.UInt128H\n" +
	"R\x06amount\x88\x01\x01\x12\x1d\n" +
	"\atimeout\x18\x1f \x01(\x04H\vR\atimeout\x88\x01\x01\x126\n" +
	"\ruser_data_128\x18( \x01(\v2\r.task.UInt128H\fR\vuserData128\x88\x01\x01\x12%\n" +
	"\fuser_data_64\x18) \x01(\x04H\rR\n" +
	"userData64\x88\x01\x01\x12%\n" +
	"\fuser_data_32\x18* \x01(\rH\x0eR\n" +
	"userData32\x88\x01\x01\x12?\n" +
	"\raccount_batch\x182 \x03(\v2\x1a.task.CreateAccountRequestR\faccountBatch\x12B\n" +
	"\x0etransfer_batch\x183 \x03(\v2\x1b.task.CreateTransferRequestR\rtransferBatch\x12,\n" +
	"\n" +
	"lookup_ids\x184 \x03(\v2\r.task.UInt128R\tlookupIds\x12\x19\n" +
	"\x05limit\x185 \x01(\rH\x0fR\x05limit\x88\x01\x01B\v\n" +
	"\t_priorityB\x0e\n" +
	"\f_retry_countB\t\n" +
	"\a_ledgerB\a\n" +
	"\x05_codeB\b\n" +
	"\x06_flagsB\r\n" +
	"\v_account_idB\x0e\n" +
	"\f_transfer_idB\x13\n" +
	"\x11_debit_account_idB\x14\n" +
	"\x12_credit_account_idB\r\n" +
	"\v_pending_idB\t\n" +
	"\a_amountB\n" +
	"\n" +
	"\b_timeoutB\x10\n" +
	"\x0e_user_data_128B\x0f\n" +
	"\r_user_data_64B\x0f\n" +
	"\r_user_data_32B\b\n" +
	"\x06_limit\"/\n" +
	"\aUInt128\x12\x10\n" +
	"\x03low\x18\x01 \x01(\x06R\x03low\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x06R\x04high\"\xc0\x02\n" +
	"\x14CreateAccountRequest\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.task.UInt128R\x02id\x12\x16\n" +
	"\x06ledger\x18\x02 \x01(\rR\x06ledger\x12\x12\n" +
	"\x04code\x18\x03 \x01(\rR\x04code\x126\n" +
	"\ruser_data_128\x18\x04 \x01(\v2\r.task.UInt128H\x00R\vuserData128\x88\x01\x01\x12%\n" +
	"\fuser_data_64\x18\x05 \x01(\x04H\x01R\n" +
	"userData64\x88\x01\x01\x12%\n" +
	"\fuser_data_32\x18\x06 \x01(\rH\x02R\n" +
	"userData32\x88\x01\x01\x12\x19\n" +
	"\x05flags\x18\a \x01(\rH\x03R\x05flags\x88\x01\x01B\x10\n" +
	"\x0e_user_data_128B\x0f\n" +
	"\r_user_data_64B\x0f\n" +
	"\r_user_data_32B\b\n" +
	"\x06_flags\"\xad\x03\n" +
	"\x15CreateTransferRequest\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.task.UInt128R\x02id\x127\n" +
	"\x10debit_account_id\x18\x02 \x01(\v2\r.task.UInt128R\x0edebitAccountId\x129\n" +
	"\x11credit_account_id\x18\x03 \x01(\v2\r.task.UInt128R\x0fcreditAccountId\x12%\n" +
	"\x06amount\x18\x04 \x01(\v2\r.task.UInt128R\x06amount\x121\n" +
	"\n" +
	"pending_id\x18\x05 \x01(\v2\r.task.UInt128H\x00R\tpendingId\x88\x01\x01\x12\x1b\n" +
	"\x06ledger\x18\x06 \x01(\rH\x01R\x06ledger\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\a \x01(\rH\x02R\x04code\x88\x01\x01\x12\x19\n" +
	"\x05flags\x18\b \x01(\rH\x03R\x05flags\x88\x01\x01\x12\x1d\n" +
	"\atimeout\x18\t \x01(\x04H\x04R\atimeout\x88\x01\x01B\r\n" +
	"\v_pending_idB\t\n" +
	"\a_ledgerB\a\n" +
	"\x05_codeB\b\n" +
	"\x06_flagsB\n" +
	"\n" +
	"\b_timeout\"\x9b\x02\n" +
	"\fTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12?\n" +
	"\x0eaccount_result\x18\x05 \x01(\v2\x13.task.AccountResultH\x00R\raccountResult\x88\x01\x01\x12B\n" +
	"\x0ftransfer_result\x18\x06 \x01(\v2\x14.task.TransferResultH\x01R\x0etransferResult\x88\x01\x01B\x11\n" +
	"\x0f_account_resultB\x12\n" +
	"\x10_transfer_result\"\xe0\x02\n" +
	"\aAccount\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.task.UInt128R\x02id\x124\n" +
	"\x0edebits_pending\x18\x02 \x01(\v2\r.task.UInt128R\rdebitsPending\x122\n" +
	"\rdebits_posted\x18\x03 \x01(\v2\r.task.UInt128R\fdebitsPosted\x126\n" +
	"\x0fcredits_pending\x18\x04 \x01(\v2\r.task.UInt128R\x0ecreditsPending\x124\n" +
	"\x0ecredits_posted\x18\x05 \x01(\v2\r.task.UInt128R\rcreditsPosted\x12\x16\n" +
	"\x06ledger\x18\x06 \x01(\rR\x06ledger\x12\x12\n" +
	"\x04code\x18\a \x01(\rR\x04code\x12\x14\n" +
	"\x05flags\x18\b \x01(\rR\x05flags\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x04R\ttimestamp\"P\n" +
	"\rAccountResult\x12)\n" +
	"\baccounts\x18\x01 \x03(\v2\r.task.AccountR\baccounts\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xa4\x02\n" +
	"\bTransfer\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.task.UInt128R\x02id\x127\n" +
	"\x10debit_account_id\x18\x02 \x01(\v2\r.task.UInt128R\x0edebitAccountId\x129\n" +
	"\x11credit_account_id\x18\x03 \x01(\v2\r.task.UInt128R\x0fcreditAccountId\x12%\n" +
	"\x06amount\x18\x04 \x01(\v2\r.task.UInt128R\x06amount\x12\x16\n" +
	"\x06ledger\x18\x05 \x01(\rR\x06ledger\x12\x12\n" +
	"\x04code\x18\x06 \x01(\rR\x04code\x12\x14\n" +
	"\x05flags\x18\a \x01(\rR\x05flags\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x04R\ttimestamp\"T\n" +
	"\x0eTransferResult\x12,\n" +
	"\ttransfers\x18\x01 \x03(\v2\x0e.task.TransferR\ttransfers\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count*\x94\x01\n" +
	"\bTaskType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x12\n" +
	"\x0eCREATE_ACCOUNT\x10\x01\x12\x12\n" +
	"\x0eBATCH_ACCOUNTS\x10\x02\x12\x13\n" +
	"\x0fLOOKUP_ACCOUNTS\x10\x03\x12\x13\n" +
	"\x0fCREATE_TRANSFER\x10\x04\x12\x13\n" +
	"\x0fBATCH_TRANSFERS\x10\x05\x12\x14\n" +
	"\x10LOOKUP_TRANSFERS\x10\x06B#Z!rrproducer/producer/models;modelsb\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_task_proto_goTypes = []any{
	(TaskType)(0),                 // 0: task.TaskType
	(*TaskRequest)(nil),           // 1: task.TaskRequest
	(*UInt128)(nil),               // 2: task.UInt128
	(*CreateAccountRequest)(nil),  // 3: task.CreateAccountRequest
	(*CreateTransferRequest)(nil), // 4: task.CreateTransferRequest
	(*TaskResponse)(nil),          // 5: task.TaskResponse
	(*Account)(nil),               // 6: task.Account
	(*AccountResult)(nil),         // 7: task.AccountResult
	(*Transfer)(nil),              // 8: task.Transfer
	(*TransferResult)(nil),        // 9: task.TransferResult
}
var file_task_proto_depIdxs = []int32{
	0,  // 0: task.TaskRequest.task_type:type_name -> task.TaskType
	2,  // 1: task.TaskRequest.account_id:type_name -> task.UInt128
	2,  // 2: task.TaskRequest.transfer_id:type_name -> task.UInt128
	2,  // 3: task.TaskRequest.debit_account_id:type_name -> task.UInt128
	2,  // 4: task.TaskRequest.credit_account_id:type_name -> task.UInt128
	2,  // 5: task.TaskRequest.pending_id:type_name -> task.UInt128
	2,  // 6: task.TaskRequest.amount:type_name -> task.UInt128
	2,  // 7: task.TaskRequest.user_data_128:type_name -> task.UInt128
	3,  // 8: task.TaskRequest.account_batch:type_name -> task.CreateAccountRequest
	4,  // 9: task.TaskRequest.transfer_batch:type_name -> task.CreateTransferRequest
	2,  // 10: task.TaskRequest.lookup_ids:type_name -> task.UInt128
	2,  // 11: task.CreateAccountRequest.id:type_name -> task.UInt128
	2,  // 12: task.CreateAccountRequest.user_data_128:type_name -> task.UInt128
	2,  // 13: task.CreateTransferRequest.id:type_name -> task.UInt128
	2,  // 14: task.CreateTransferRequest.debit_account_id:type_name -> task.UInt128
	2,  // 15: task.CreateTransferRequest.credit_account_id:type_name -> task.UInt128
	2,  // 16: task.CreateTransferRequest.amount:type_name -> task.UInt128
	2,  // 17: task.CreateTransferRequest.pending_id:type_name -> task.UInt128
	7,  // 18: task.TaskResponse.account_result:type_name -> task.AccountResult
	9,  // 19: task.TaskResponse.transfer_result:type_name -> task.TransferResult
	2,  // 20: task.Account.id:type_name -> task.UInt128
	2,  // 21: task.Account.debits_pending:type_name -> task.UInt128
	2,  // 22: task.Account.debits_posted:type_name -> task.UInt128
	2,  // 23: task.Account.credits_pending:type_name -> task.UInt128
	2,  // 24: task.Account.credits_posted:type_name -> task.UInt128
	6,  // 25: task.AccountResult.accounts:type_name -> task.Account
	2,  // 26: task.Transfer.id:type_name -> task.UInt128
	2,  // 27: task.Transfer.debit_account_id:type_name -> task.UInt128
	2,  // 28: task.Transfer.credit_account_id:type_name -> task.UInt128
	2,  // 29: task.Transfer.amount:type_name -> task.UInt128
	8,  // 30: task.TransferResult.transfers:type_name -> task.Transfer
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	file_task_proto_msgTypes[0].OneofWrappers = []any{}
	file_task_proto_msgTypes[2].OneofWrappers = []any{}
	file_task_proto_msgTypes[3].OneofWrappers = []any{}
	file_task_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		EnumInfos:         file_task_proto_enumTypes,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
