// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: task.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED TransactionStatus = 0
	TransactionStatus_TRANSACTION_STATUS_PENDING     TransactionStatus = 1
	TransactionStatus_TRANSACTION_STATUS_COMPLETED   TransactionStatus = 2
	TransactionStatus_TRANSACTION_STATUS_FAILED      TransactionStatus = 3
	TransactionStatus_TRANSACTION_STATUS_REVOKED     TransactionStatus = 4
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNSPECIFIED",
		1: "TRANSACTION_STATUS_PENDING",
		2: "TRANSACTION_STATUS_COMPLETED",
		3: "TRANSACTION_STATUS_FAILED",
		4: "TRANSACTION_STATUS_REVOKED",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNSPECIFIED": 0,
		"TRANSACTION_STATUS_PENDING":     1,
		"TRANSACTION_STATUS_COMPLETED":   2,
		"TRANSACTION_STATUS_FAILED":      3,
		"TRANSACTION_STATUS_REVOKED":     4,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[0].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[0]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskType      string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload       *Payload               `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Priority      *uint32                `protobuf:"varint,6,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	RetryCount    *int32                 `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3,oneof" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *TaskRequest) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TaskRequest) GetPriority() uint32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *TaskRequest) GetRetryCount() int32 {
	if x != nil && x.RetryCount != nil {
		return *x.RetryCount
	}
	return 0
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskType      string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskResponse) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UInt128 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Low           uint64                 `protobuf:"fixed64,1,opt,name=low,proto3" json:"low,omitempty"`
	High          uint64                 `protobuf:"fixed64,2,opt,name=high,proto3" json:"high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UInt128) Reset() {
	*x = UInt128{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UInt128) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInt128) ProtoMessage() {}

func (x *UInt128) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInt128.ProtoReflect.Descriptor instead.
func (*UInt128) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *UInt128) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *UInt128) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UInt128               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ledger        uint32                 `protobuf:"varint,2,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Code          uint32                 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	UserData_128  *UInt128               `protobuf:"bytes,4,opt,name=user_data_128,json=userData128,proto3" json:"user_data_128,omitempty"`
	UserData_64   uint64                 `protobuf:"varint,5,opt,name=user_data_64,json=userData64,proto3" json:"user_data_64,omitempty"`
	UserData_32   uint32                 `protobuf:"varint,6,opt,name=user_data_32,json=userData32,proto3" json:"user_data_32,omitempty"`
	Flags         uint32                 `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountRequest) GetId() *UInt128 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateAccountRequest) GetLedger() uint32 {
	if x != nil {
		return x.Ledger
	}
	return 0
}

func (x *CreateAccountRequest) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateAccountRequest) GetUserData_128() *UInt128 {
	if x != nil {
		return x.UserData_128
	}
	return nil
}

func (x *CreateAccountRequest) GetUserData_64() uint64 {
	if x != nil {
		return x.UserData_64
	}
	return 0
}

func (x *CreateAccountRequest) GetUserData_32() uint32 {
	if x != nil {
		return x.UserData_32
	}
	return 0
}

func (x *CreateAccountRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type CreateTransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              *UInt128               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DebitAccountId  *UInt128               `protobuf:"bytes,2,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId *UInt128               `protobuf:"bytes,3,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          *UInt128               `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Ledger          uint32                 `protobuf:"varint,5,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Code            uint32                 `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`
	Flags           uint32                 `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTransferRequest) GetId() *UInt128 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateTransferRequest) GetDebitAccountId() *UInt128 {
	if x != nil {
		return x.DebitAccountId
	}
	return nil
}

func (x *CreateTransferRequest) GetCreditAccountId() *UInt128 {
	if x != nil {
		return x.CreditAccountId
	}
	return nil
}

func (x *CreateTransferRequest) GetAmount() *UInt128 {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateTransferRequest) GetLedger() uint32 {
	if x != nil {
		return x.Ledger
	}
	return 0
}

func (x *CreateTransferRequest) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateTransferRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type Payload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Operation:
	//
	//	*Payload_CreateAccount
	//	*Payload_CreateTransfer
	Operation     isPayload_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

func (x *Payload) GetOperation() isPayload_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Payload) GetCreateAccount() *CreateAccountRequest {
	if x != nil {
		if x, ok := x.Operation.(*Payload_CreateAccount); ok {
			return x.CreateAccount
		}
	}
	return nil
}

func (x *Payload) GetCreateTransfer() *CreateTransferRequest {
	if x != nil {
		if x, ok := x.Operation.(*Payload_CreateTransfer); ok {
			return x.CreateTransfer
		}
	}
	return nil
}

type isPayload_Operation interface {
	isPayload_Operation()
}

type Payload_CreateAccount struct {
	CreateAccount *CreateAccountRequest `protobuf:"bytes,1,opt,name=create_account,json=createAccount,proto3,oneof"`
}

type Payload_CreateTransfer struct {
	CreateTransfer *CreateTransferRequest `protobuf:"bytes,2,opt,name=create_transfer,json=createTransfer,proto3,oneof"`
}

func (*Payload_CreateAccount) isPayload_Operation() {}

func (*Payload_CreateTransfer) isPayload_Operation() {}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\x04task\"\x89\x02\n" +
	"\vTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12'\n" +
	"\apayload\x18\x04 \x01(\v2\r.task.PayloadR\apayload\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\bpriority\x18\x06 \x01(\rH\x00R\bpriority\x88\x01\x01\x12$\n" +
	"\vretry_count\x18\a \x01(\x05H\x01R\n" +
	"retryCount\x88\x01\x01B\v\n" +
	"\t_priorityB\x0e\n" +
	"\f_retry_count\"o\n" +
	"\fTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"/\n" +
	"\aUInt128\x12\x10\n" +
	"\x03low\x18\x01 \x01(\x06R\x03low\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x06R\x04high\"\xee\x01\n" +
	"\x14CreateAccountRequest\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.task.UInt128R\x02id\x12\x16\n" +
	"\x06ledger\x18\x02 \x01(\rR\x06ledger\x12\x12\n" +
	"\x04code\x18\x03 \x01(\rR\x04code\x121\n" +
	"\ruser_data_128\x18\x04 \x01(\v2\r.task.UInt128R\vuserData128\x12 \n" +
	"\fuser_data_64\x18\x05 \x01(\x04R\n" +
	"userData64\x12 \n" +
	"\fuser_data_32\x18\x06 \x01(\rR\n" +
	"userData32\x12\x14\n" +
	"\x05flags\x18\a \x01(\rR\x05flags\"\x93\x02\n" +
	"\x15CreateTransferRequest\x12\x1d\n" +
	"\x02id\x18\x01 \x01(\v2\r.task.UInt128R\x02id\x127\n" +
	"\x10debit_account_id\x18\x02 \x01(\v2\r.task.UInt128R\x0edebitAccountId\x129\n" +
	"\x11credit_account_id\x18\x03 \x01(\v2\r.task.UInt128R\x0fcreditAccountId\x12%\n" +
	"\x06amount\x18\x04 \x01(\v2\r.task.UInt128R\x06amount\x12\x16\n" +
	"\x06ledger\x18\x05 \x01(\rR\x06ledger\x12\x12\n" +
	"\x04code\x18\x06 \x01(\rR\x04code\x12\x14\n" +
	"\x05flags\x18\a \x01(\rR\x05flags\"\xa3\x01\n" +
	"\aPayload\x12C\n" +
	"\x0ecreate_account\x18\x01 \x01(\v2\x1a.task.CreateAccountRequestH\x00R\rcreateAccount\x12F\n" +
	"\x0fcreate_transfer\x18\x02 \x01(\v2\x1b.task.CreateTransferRequestH\x00R\x0ecreateTransferB\v\n" +
	"\toperation*\xb8\x01\n" +
	"\x11TransactionStatus\x12\"\n" +
	"\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cTRANSACTION_STATUS_COMPLETED\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_STATUS_FAILED\x10\x03\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_REVOKED\x10\x0425\n" +
	"\x04Task\x12-\n" +
	"\x04Send\x12\x11.task.TaskRequest\x1a\x12.task.TaskResponseB#Z!rrproducer/producer/models;modelsb\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_task_proto_goTypes = []any{
	(TransactionStatus)(0),        // 0: task.TransactionStatus
	(*TaskRequest)(nil),           // 1: task.TaskRequest
	(*TaskResponse)(nil),          // 2: task.TaskResponse
	(*UInt128)(nil),               // 3: task.UInt128
	(*CreateAccountRequest)(nil),  // 4: task.CreateAccountRequest
	(*CreateTransferRequest)(nil), // 5: task.CreateTransferRequest
	(*Payload)(nil),               // 6: task.Payload
}
var file_task_proto_depIdxs = []int32{
	6,  // 0: task.TaskRequest.payload:type_name -> task.Payload
	3,  // 1: task.CreateAccountRequest.id:type_name -> task.UInt128
	3,  // 2: task.CreateAccountRequest.user_data_128:type_name -> task.UInt128
	3,  // 3: task.CreateTransferRequest.id:type_name -> task.UInt128
	3,  // 4: task.CreateTransferRequest.debit_account_id:type_name -> task.UInt128
	3,  // 5: task.CreateTransferRequest.credit_account_id:type_name -> task.UInt128
	3,  // 6: task.CreateTransferRequest.amount:type_name -> task.UInt128
	4,  // 7: task.Payload.create_account:type_name -> task.CreateAccountRequest
	5,  // 8: task.Payload.create_transfer:type_name -> task.CreateTransferRequest
	1,  // 9: task.Task.Send:input_type -> task.TaskRequest
	2,  // 10: task.Task.Send:output_type -> task.TaskResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	file_task_proto_msgTypes[0].OneofWrappers = []any{}
	file_task_proto_msgTypes[5].OneofWrappers = []any{
		(*Payload_CreateAccount)(nil),
		(*Payload_CreateTransfer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		EnumInfos:         file_task_proto_enumTypes,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
